[package]
name = "aigen_macros"
authors = ["Neeraj Gupta <neerajg1320@gmail.com>"]
description = "Procedural macros for testing"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn={ version = "2.0.52", features = ["full"] }


